### ISSUE TITLE
Search box  doesn't work

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#13]
Try to search anything on search box , its not working 
![image](https://user-images.githubusercontent.com/24386802/64354530-e9585080-cfff-11e9-860a-ff0710613e90.png)

**Comment by rkhamis** [comment]
@Dinaamagdy I tried it and it works. what did you expect to see?

**Comment by rkhamis** [comment]
seems not to work with other people, my mistake

**Comment by abom** [comment]
Can you add more details? console logs...etc.

**Comment by Dinaamagdy** [comment]
consol logs 
```
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
sonic_client.js:10 Object
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
sonic_client.js:10 Object
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
sonic_client.js:10 Object
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
sonic_client.js:10 {namespace: "default", actor: "sonic", command: "query", args: {…}, headers: {…}}
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
connect.then @ gedis_client.js:24
Promise.then (async)
execute @ gedis_client.js:23
client.execute @ gedis_client.js:38
sonic_search @ sonic_client.js:11
doSearch @ search.js:241
(anonymous) @ search.js:275
setTimeout (async)
(anonymous) @ search.js:275
sonic_client.js:10 {namespace: "default", actor: "sonic", command: "query", args: {…}, headers: {…}}
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
connect.then @ gedis_client.js:24
Promise.then (async)
execute @ gedis_client.js:23
client.execute @ gedis_client.js:38
sonic_search @ sonic_client.js:11
doSearch @ search.js:241
(anonymous) @ search.js:275
setTimeout (async)
(anonymous) @ search.js:275
sonic_client.js:10 {namespace: "default", actor: "sonic", command: "query", args: {…}, headers: {…}}
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
connect.then @ gedis_client.js:24
Promise.then (async)
execute @ gedis_client.js:23
client.execute @ gedis_client.js:38
sonic_search @ sonic_client.js:11
doSearch @ search.js:241
(anonymous) @ search.js:275
setTimeout (async)
(anonymous) @ search.js:275
sonic_client.js:10 {namespace: "default", actor: "sonic", command: "query", args: {…}, headers: {…}}
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
connect.then @ gedis_client.js:24
Promise.then (async)
execute @ gedis_client.js:23
client.execute @ gedis_client.js:38
sonic_search @ sonic_client.js:11
doSearch @ search.js:241
(anonymous) @ search.js:275
setTimeout (async)
(anonymous) @ search.js:275
sonic_client.js:10 {namespace: "default", actor: "sonic", command: "query", args: {…}, headers: {…}}
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
connect.then @ gedis_client.js:24
Promise.then (async)
execute @ gedis_client.js:23
client.execute @ gedis_client.js:38
sonic_search @ sonic_client.js:11
doSearch @ search.js:241
(anonymous) @ search.js:275
setTimeout (async)
(anonymous) @ search.js:275
sonic_client.js:10 {namespace: "default", actor: "sonic", command: "query", args: {…}, headers: {…}}
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
connect.then @ gedis_client.js:24
Promise.then (async)
execute @ gedis_client.js:23
client.execute @ gedis_client.js:38
sonic_search @ sonic_client.js:11
doSearch @ search.js:241
(anonymous) @ search.js:275
setTimeout (async)
(anonymous) @ search.js:275
sonic_client.js:10 {namespace: "default", actor: "sonic", command: "query", args: {…}, headers: {…}}
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
connect.then @ gedis_client.js:24
Promise.then (async)
execute @ gedis_client.js:23
client.execute @ gedis_client.js:38
sonic_search @ sonic_client.js:11
doSearch @ search.js:241
(anonymous) @ search.js:275
setTimeout (async)
(anonymous) @ search.js:275
sonic_client.js:10 {namespace: "default", actor: "sonic", command: "query", args: {…}, headers: {…}}
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
connect.then @ gedis_client.js:24
Promise.then (async)
execute @ gedis_client.js:23
client.execute @ gedis_client.js:38
sonic_search @ sonic_client.js:11
doSearch @ search.js:241
(anonymous) @ search.js:275
setTimeout (async)
(anonymous) @ search.js:275
sonic_client.js:10 {namespace: "default", actor: "sonic", command: "query", args: {…}, headers: {…}}
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
connect.then @ gedis_client.js:24
Promise.then (async)
execute @ gedis_client.js:23
client.execute @ gedis_client.js:38
sonic_search @ sonic_client.js:11
doSearch @ search.js:241
(anonymous) @ search.js:275
setTimeout (async)
(anonymous) @ search.js:275
sonic_client.js:10 {namespace: "default", actor: "sonic", command: "query", args: {…}, headers: {…}}
gedis_client.js:30 WebSocket is already in CLOSING or CLOSED state.
Promise @ gedis_client.js:30
connect.then @ gedis_client.js:24
Promise.then (async)
execute @ gedis_client.js:23
client.execute @ gedis_client.js:38
sonic_search @ sonic_client.js:11
doSearch @ search.js:241
(anonymous) @ search.js:275
setTimeout (async)
(anonymous) @ search.js:275
favicon.ico:1 GET http://172.17.0.2/favicon.ico 500 (Internal Server Error)`
```

**Comment by abom** [comment]
Loading wikis inside myjobs is borken, see https://github.com/threefoldtech/jumpscaleX_core/issues/60.

**Comment by abom** [comment]
Seems like there's an error when in bcdb seach, after loading

```
j.sal.bcdbfs.search('new', location='/docsites')
```

Raises an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/sal/bcdbfs/BCDBFS.py", line 290, in search
    obj.name[len(location) + 1 : -3] for obj in self._file_model.search(text) if obj.name.startswith(location)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 308, in search
    res.append(self.get(int(parts[0])))
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBDecorator.py", line 60, in wrapper_queue_method
    res = func(*args, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 536, in get
    obj_id, self
Jumpscale.core.InstallTools.JSExceptions.__init__.<locals>.JSBUG1: ?[1;31mEXCEPTION: 
    no object with id 941 found in model:jumpscale.bcdb.fs.file.2
    , this means the index gave back an id which is not part of this model.?[0;0m

?[1;31mEXCEPTION: 
    no object with id 941 found in model:jumpscale.bcdb.fs.file.2
    , this means the index gave back an id which is not part of this model.?[0;0m
```

Will try to clean bcdb, load wikis, then search again.

**Comment by abom** [comment]
> Will try to clean bcdb, load wikis, then search again.

Still the same problem.

**Comment by abom** [comment]
> Will try to clean bcdb, load wikis, then search again.

Search works without problems, the thing is when clearing bcdb, you need to clear sonic too by doing:

`j.servers.sonic.default.destroy() `

**Comment by Dinaamagdy** [comment]
works in 
```
jumpscalex_core : 79a930098d114fbf43c98c5d5525d0ed7b599f98
jumpscalex_libs : development
jumpsccalex_threeboot: development
```
