### ISSUE TITLE
wiki-load : without -f raise error  

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_threebot#242]
## Steps :
- start threebot : j.serves.threebot.local_start_default()
```
jsx wiki-load -u https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/docs/wikis/examples/docs -n examples 
```
## Error 
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDB.py", line 275, in redis_server_start
    self.redis_server.start()
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/connectors/redis/RedisServer.py", line 67, in start
    self.gevent_server.serve_forever()
  File "/usr/local/lib/python3.6/dist-packages/gevent/baseserver.py", line 367, in serve_forever
    self.start()
  File "/usr/local/lib/python3.6/dist-packages/gevent/baseserver.py", line 305, in start
    self.init_socket()
  File "/usr/local/lib/python3.6/dist-packages/gevent/server.py", line 146, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/usr/local/lib/python3.6/dist-packages/gevent/server.py", line 157, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/usr/local/lib/python3.6/dist-packages/gevent/server.py", line 256, in _tcp_listener
    sock.bind(address)
OSError: [Errno 98] Address already in use: ('0.0.0.0', 6385)
2019-11-14T13:16:30Z <Greenlet at 0x7f4abb571848: <bound method BCDB.redis_server_start of bcdb:myjobs
>(port=6385)> failed with OSError

Thu 14 13:16:30 c28b62fa9a5cf998c.py -  31 - b_ede010359363515c28b62fa9a5cf998c : init index:jumpscale.myjobs.job
Thu 14 13:16:30 129577613d9be1f27.py -  31 - n_2c467e8e2116e34129577613d9be1f27 : init index:jumpscale.myjobs.action
Thu 14 13:16:30 ers/myjobs/MyJobs.py - 117 - wait                               : EXCEPTION: 
    This operation would block forever
            Hub: <Hub '' at 0x7f4ac5f626d8 epoll default pending=0 ref=0 fileno=5 resolver=<gevent.resolver_thread.Resolver
        at 0x7f4ac53da4e0 pool=<ThreadPool at 0x7f4ac53da518 0/1/10 hub=<Hub at 0x7f4ac5f626d8
        thread_ident=0x139959217690432>>> threadpool=<ThreadPool at 0x7f4ac53da518 0/1/10 hub=<Hub at 0x7f4ac5f626d8
        thread_ident=0x139959217690432>> thread_ident=0x7f4acb741740>
            Handles:
    []
--TRACEBACK------------------
/sandbox/bin/jsx in <module>
    886    cli()
/sandbox/bin/jsx in wiki_load
    450    j.servers.myjobs.wait(job_ids, timeout=None, die=False)
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobsFactory.py in wait
    528    job.wait(die=die)
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobs.py in wait
    117    event.wait(timeout)
-----------------------------

Thu 14 13:16:31 BCDB.py              - 340 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK
Thu 14 13:16:32 BCDB.py              - 340 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK
```

**Comment by xmonader** [comment]
moving myjobs to start with the threebot process and not in the myjobs package breaks the `wait` and we need to use redis lock or to be done from actor for that. either be fixed today or moved into the next milestone and `-f` is the only way to use it

**Comment by xmonader** [comment]
fixed in https://github.com/threefoldtech/jumpscaleX_threebot/pull/248 and using actor to do the loading

**Comment by siddiquagig** [comment]
Verified 

Wiki is loaded using -f 

![image](https://user-images.githubusercontent.com/25789724/69006191-0042e980-0945-11ea-8170-0b449e692e1e.png)

**Comment by abom** [comment]
@siddiquagig `-f` was already working, it means that it was broken without `-f`.

**Comment by abom** [comment]
@siddiquagig `-f` was already working, it means that it was broken without `-f`.

**Comment by siddiquagig** [comment]
Yes tested without the -f option , it is working fine now

![image](https://user-images.githubusercontent.com/25789724/69007651-fa0b3800-0959-11ea-9400-5583b7b578fa.png)
![image](https://user-images.githubusercontent.com/25789724/69007657-05f6fa00-095a-11ea-852d-9bd31a2cef74.png)
