### ISSUE TITLE
error while starting 3bot server

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_threebot#257]
```bash
kosmos -p 'j.servers.threebot.local_start_default()'
```

Gives:

```
*****Remote Exception*****                                                                                                                          
Error in sys.excepthook:
Traceback (most recent call last):
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 3586, in excepthook
    Tools.log2stdout(logdict)
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1909, in log2stdout
    if not show():
  File "/sandbox/lib/jumpscale/Jumpscale/core/InstallTools.py", line 1903, in show
    if MyEnv.debug or logdict["level"] >= 50:
KeyError: 'level'

Original exception was:
Traceback (most recent call last):
  File "/sandbox/var/codegen/gedis/threebot/client/default_package_manager.py", line 42, in package_add
    res = self._redis.execute_command(cmd_name,data)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 853, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 718, in read_response
    raise response
redis.exceptions.ResponseError: {"message": "not authorized Couldn't find actor with name: package_manager", "actor_name": "package_manager", "cmd_name": "package_add", "threebot_id": null}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sandbox/bin/kosmos", line 175, in <module>
    exec(toexec, globals(), j._locals_get({}))
  File "<string>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/servers/threebot/ThreeBotServersFactory.py", line 91, in local_start_default
    path="/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/webplatform/"
  File "/sandbox/var/codegen/gedis/threebot/client/default_package_manager.py", line 44, in package_add
    self.handle_error(e,1,cmd_name=cmd_name)
  File "/sandbox/var/codegen/gedis/threebot/client/default_package_manager.py", line 274, in handle_error
    raise j.exceptions.RemoteException(message=msg, data=logdict, exception=e)
Jumpscale.core.InstallTools.RemoteException1: None
Sun 17 16:32:25 BCDB.py              - 340 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK
```

**Comment by abom** [comment]
Branches switching seems to be the cause, closing as newer installation does not have this issue.
