### ISSUE TITLE
searching wikis doesn't work

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_threebot#324]
it always returns empty set 

might be related to doing the search in bcdbfs?
![image](https://user-images.githubusercontent.com/64129/71558043-6bf59780-2a57-11ea-98be-0dbf02ca6d4b.png)

**Comment by abom** [comment]
Cannot load wikis due to bcdb errors, i now get a sonic client using the information from `threebot` sonic server, but still cannot test it properly.

One of the errors:

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.6/dist-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/connectors/redis/RedisServer.py", line 83, in handle_redis
    self._handle_redis(socket, address, parser, response)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/connectors/redis/RedisServer.py", line 152, in _handle_redis
    method(response, *args)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/connectors/redis/RedisServer.py", line 205, in bcdb_model_init
    model = bcdb.model_get(url=url)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDB.py", line 520, in model_get
    self.model_add(model)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDB.py", line 583, in model_add
    self._schema_property_add_if_needed(model.schema)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDB.py", line 608, in _schema_property_add_if_needed
    s = prop.jumpscaletype._schema
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/JSXObjectTypeFactory.py", line 34, in _schema
    s = j.data.schema.get_from_url(url=self._default)
  File "/sandbox/lib/jumpscale/Jumpscale/data/schema/SchemaFactory.py", line 124, in get_from_url
    raise j.exceptions.Input("Could not find schema with url:%s" % url)
Jumpscale.core.InstallTools.JSExceptions.__init__.<locals>.Input1: None
```

Other errors also occur, like `cannot write to read-only databse`...etc.

**Comment by xmonader** [comment]
done on development_fixes3 and verified.
